# 1 Dimensional Tensors

In [1]:
import torch
import numpy as np

In [2]:
v = torch.tensor([1, 2, 3, 4, 5, 6])
print(v)
print(v.dtype)
print(v.type())

tensor([1, 2, 3, 4, 5, 6])
torch.int64
torch.LongTensor


In [3]:
print(v[0])
print(v[1:-1])
print(v[-1])

tensor(1)
tensor([2, 3, 4, 5])
tensor(6)


In [4]:
f = torch.FloatTensor([1, 2, 3, 4, 5, 6])
print(f)
print(f.dtype)
print(f.type())

tensor([1., 2., 3., 4., 5., 6.])
torch.float32
torch.FloatTensor


In [5]:
v.view(6, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [6]:
v.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [7]:
v.view(3, -1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [8]:
a = np.array([1, 2, 3, 4, 5, 6])
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5, 6])
torch.LongTensor


In [21]:
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)
print(type(numpy_cnv))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
