# Importing the Libraries

In [1]:
import torch
from torch.nn import Linear

# Making Predictions

In [2]:
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

In [3]:
def forward(x):
    y = w * x + b
    return y

In [4]:
x = torch.tensor(2)
print(forward(x))

tensor(7., grad_fn=<AddBackward0>)


In [5]:
x = torch.tensor([[4], [7]])
print(forward(x))

tensor([[13.],
        [22.]], grad_fn=<AddBackward0>)


# Linear Class

In [6]:
torch.manual_seed(1)
model = Linear(in_features = 1, out_features = 1)
print(model.weight, model.bias)

Parameter containing:
tensor([[0.5153]], requires_grad=True) Parameter containing:
tensor([-0.4414], requires_grad=True)


In [ ]:
x = torch.tensor([2.0])