# Importing the Libraries

In [11]:
import torch
import torch.nn as nn
from torch.nn import Linear

# Making Predictions

In [2]:
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

In [3]:
def forward(x):
    y = w * x + b
    return y

In [4]:
x = torch.tensor(2)
print(forward(x))

tensor(7., grad_fn=<AddBackward0>)


In [5]:
x = torch.tensor([[4], [7]])
print(forward(x))

tensor([[13.],
        [22.]], grad_fn=<AddBackward0>)


# Linear Class

In [6]:
torch.manual_seed(1)
model = Linear(in_features = 1, out_features = 1)
print(model.weight, model.bias)

Parameter containing:
tensor([[0.5153]], requires_grad=True) Parameter containing:
tensor([-0.4414], requires_grad=True)


In [9]:
x = torch.tensor([2.0])
print(model(x))

tensor([0.5891], grad_fn=<AddBackward0>)


In [10]:
x = torch.tensor([[2.0], [3.3]])
print(model(x))

tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward0>)


# Custom Modules

In [22]:
class LR(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__()
        self.linear = Linear(input_size, output_size)
    def forward(self, x):
        pred = self.linear(x)
        return pred

In [23]:
torch.manual_seed(1)
model = LR(1, 1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [28]:
x = torch.tensor([1.0])
print(model.forward(x))

tensor([0.0739], grad_fn=<AddBackward0>)


In [29]:
x = torch.tensor([[1.0], [2.0]])
print(model.forward(x))

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward0>)


# Creating Dataset